### ISSUE TITLE
About Falcon's IDE and feature for making stand alone EXEs.

### ISSUE THREAD

**Issue by vinodvinu** [falconpl/falcon#1]
Hi Falcon team,
I am a hobby programmer. Falcon looks like a nice language.  But i didn't tried this yet. I have two questions before trying.
1. Does Falcon comes with an IDE ? A feature rich IDE will help a learner to grasp the language details easily.
2. If there is an IDE, then does it able to make stand alone EXEs from Falcon code ?

**Comment by TheDcoder** [comment]
This repository hasn't been updated for 4 years, I don't think they care anymore...

**Comment by vinodvinu** [comment]
Oh Dcoder, Glad to see you here.

**Comment by TheDcoder** [comment]
😉
