### ISSUE TITLE
libfalcon_engine.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ZianElijahSmith** [falconpl/falcon#9]
This might possibly be an issue on my part.

I downloaded a copy of the source code directly from this Github.
I was able to compile it (which is nice, the source code from the website does not compile).

After running:
  sudo  make install
  sudo make

I found the falcon binary. After trying to run the falcon binary, I receive the following message.

~/FalconPL/Falcon1/falcon-master/build/bin$ falcon
falcon: error while loading shared libraries: libfalcon_engine.so.1: cannot open shared object file: No such file or directory

Is this an issue where I made a mistake? Or is this an issue where something in the source code needs to be updated?
For reference, I compiled on Debian 10. I have used terminal commands to trying to find libfalcon_engine.so.1, but can't find it.

**Comment by astrorigin** [comment]
You can fix by adding the ``lib`` directory where you installed Falcon to the cache of shared libraries:

``echo "/INSTALL_PREFIX/lib" | sudo tee -a /etc/ld.so.conf.d/falcon.conf > /dev/null``
``sudo ldconfig``

**Comment by ZianElijahSmith** [comment]
That fixed it.

![falcon](https://user-images.githubusercontent.com/121137084/221494807-8a10e785-d876-4a10-a438-c348a71397f4.png)

Thank you very much, the issue is fixed and I have falcon running. Thanks again!
